server:
  port: 9000

spring:
  application:
    name: hexo-image-cleaner
  thymeleaf:
    enabled: true
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8

image:
  directory: "C:\\Users\\sfuli\\Desktop\\11\\"